# vim8_install/tasks/main.yml
---
- name: Gathering facts
  setup:

- name: Assert that this is EL 7 Linux
  assert:
    that:
      - ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"
    success_msg: 'EL 7 detected, installing Vim from source'
    fail_msg: 'This role only supports CentOS 7 or RHEL 7 for now'

- name: Checking for existing Vim 8
  stat:
    path: /usr/local/bin/vim
  register: vimcheck

- name: Installing Vim
  block:
    - name: Installing dependencies
      yum:
        name:
          - autoconf
          - gcc
          - git
          - make
          - ncurses-devel
          - automake
        state: installed

    - name: Cloning Vim Github repo
      git:
        repo: https://github.com/vim/vim.git
        version: master
        dest: /tmp/vim8

    - name: Running make
      make:
        chdir: /tmp/vim8/src

    - name: Running make install
      make:
        chdir: /tmp/vim8/src
        target: install

    - name: Cleaning up
      file:
        path: /tmp/vim8
        state: absent
  when: not vimcheck.stat.exists

- name: Creating /etc/profile.d/vim.sh
  copy:
    content: |
      PATH=/usr/local/bin:$PATH;export PATH
    dest: /etc/profile.d/vim.sh
    owner: root
    group: root
    mode: 0644
...
